export default {
	port: process.env.PORT,
	host: process.env.HOST,
    enc_salt: process.env.ENC_SALT,
	enc_algorithm: process.env.ENC_ALGO,
	jwt_secret: process.env.JWT_SECRET,
	jwt_algorithm: process.env.JWT_ALGO,
	jwt_expires_in: process.env.JWT_EXPIRES_IN,
	google_client_id: process.env.GOOGLE_CLIENT_ID,
	run_mode: process.env.RUN_MODE,
    pg_user_name: process.env.PG_USER_NAME,
	pg_password: process.env.PG_PASSWORD,
	pg_db_name: process.env.PG_DBNAME,
	pg_host: process.env.PG_HOST,
	pg_port: process.env.PG_PORT,
}
